import type { UnitCode } from "@/lib/units";
import type { ExpenseCategory } from "@/schemas/expense";

/** A small Bangladeshi general store: names in English and Bangla, taka prices, realistic stock. */

export interface SeedProduct {
  name: string;
  nameBn: string;
  category: string;
  unit: UnitCode;
  /** Taka per unit. */
  buy: number;
  sell: number;
  /** Rough units sold per day (also how likely it is to be picked). */
  daily: number;
  /** Stock to have at the end of the month, in units (the monthly stock count sets it). */
  endStock: number;
  /** Warn when stock falls to this many units. */
  low: number;
  supplier: number;
}

export const CATEGORIES = [
  { name: "Rice & Pulses", nameBn: "চাল-ডাল" },
  { name: "Oil & Spices", nameBn: "তেল-মসলা" },
  { name: "Vegetables & Eggs", nameBn: "সবজি ও ডিম" },
  { name: "Dairy & Drinks", nameBn: "দুধ ও পানীয়" },
  { name: "Snacks & Tea", nameBn: "স্ন্যাকস ও চা" },
  { name: "Soap & Care", nameBn: "সাবান ও প্রসাধনী" },
  { name: "Household", nameBn: "গৃহস্থালি" },
] as const;

export const SUPPLIERS = [
  {
    name: "Karim Traders",
    nameBn: "করিম ট্রেডার্স",
    phone: "01711000101",
    contactPerson: "আব্দুল করিম",
    address: "বাবুবাজার, ঢাকা",
  },
  {
    name: "Al-Amin Enterprise",
    nameBn: "আল-আমিন এন্টারপ্রাইজ",
    phone: "01811000202",
    contactPerson: "আল-আমিন",
    address: "মৌলভীবাজার, ঢাকা",
  },
  {
    name: "Rahman Distribution",
    nameBn: "রহমান ডিস্ট্রিবিউশন",
    phone: "01911000303",
    contactPerson: "মিজানুর রহমান",
    address: "কারওয়ান বাজার, ঢাকা",
  },
  {
    name: "Ma-Moni Cosmetics",
    nameBn: "মা-মনি কসমেটিক্স",
    phone: "01611000404",
    contactPerson: "শিরিন আক্তার",
    address: "নিউ মার্কেট, ঢাকা",
  },
] as const;

export const CUSTOMERS = [
  { name: "রহিম উদ্দিন", phone: "01711000001", address: "বাড়ি ১২, মিরপুর-১০" },
  { name: "করিম মিয়া", phone: "01711000002", address: "বাড়ি ৪, মিরপুর-১০" },
  { name: "সালমা খাতুন", phone: "01811000003", address: "ফ্ল্যাট ৩বি, মিরপুর-১১" },
  { name: "জহুরুল ইসলাম", phone: "01911000004", address: "মিরপুর-১২" },
  { name: "নাসরিন আক্তার", phone: "01611000005", address: "বাড়ি ৯, মিরপুর-১০" },
  { name: "মোঃ আলমগীর", phone: "01711000006", address: "পল্লবী, মিরপুর" },
  { name: "ফাতেমা বেগম", phone: "01811000007", address: "বাড়ি ২২, মিরপুর-১১" },
  { name: "হাসান মাহমুদ", phone: "01911000008", address: "মিরপুর-১০, গোল চত্বর" },
] as const;

// supplier index: 0 Karim (rice, pulses, sugar, veg) · 1 Al-Amin (oil, spices, snacks) · 2 Rahman (dairy, drinks, household) · 3 Ma-Moni (care)
export const PRODUCTS: SeedProduct[] = [
  {
    name: "Miniket Rice",
    nameBn: "মিনিকেট চাল",
    category: "Rice & Pulses",
    unit: "kg",
    buy: 68,
    sell: 75,
    daily: 14,
    endStock: 180,
    low: 50,
    supplier: 0,
  },
  {
    name: "Nazirshail Rice",
    nameBn: "নাজিরশাইল চাল",
    category: "Rice & Pulses",
    unit: "kg",
    buy: 78,
    sell: 85,
    daily: 8,
    endStock: 120,
    low: 40,
    supplier: 0,
  },
  {
    name: "Masoor Dal",
    nameBn: "মসুর ডাল",
    category: "Rice & Pulses",
    unit: "kg",
    buy: 105,
    sell: 120,
    daily: 4,
    endStock: 45,
    low: 15,
    supplier: 0,
  },
  {
    name: "Moog Dal",
    nameBn: "মুগ ডাল",
    category: "Rice & Pulses",
    unit: "kg",
    buy: 130,
    sell: 150,
    daily: 2,
    endStock: 22,
    low: 10,
    supplier: 0,
  },
  {
    name: "Chickpeas",
    nameBn: "ছোলা",
    category: "Rice & Pulses",
    unit: "kg",
    buy: 95,
    sell: 110,
    daily: 2,
    endStock: 25,
    low: 10,
    supplier: 0,
  },
  {
    name: "Sugar",
    nameBn: "চিনি",
    category: "Rice & Pulses",
    unit: "kg",
    buy: 118,
    sell: 130,
    daily: 7,
    endStock: 60,
    low: 20,
    supplier: 0,
  },
  {
    name: "Soyabean Oil 1L",
    nameBn: "সয়াবিন তেল (১ লিটার)",
    category: "Oil & Spices",
    unit: "bottle",
    buy: 168,
    sell: 180,
    daily: 5,
    endStock: 34,
    low: 10,
    supplier: 1,
  },
  {
    name: "Soyabean Oil 5L",
    nameBn: "সয়াবিন তেল (৫ লিটার)",
    category: "Oil & Spices",
    unit: "bottle",
    buy: 830,
    sell: 870,
    daily: 1,
    endStock: 9,
    low: 3,
    supplier: 1,
  },
  {
    name: "Mustard Oil 500ml",
    nameBn: "সরিষার তেল (৫০০ মি.লি.)",
    category: "Oil & Spices",
    unit: "bottle",
    buy: 150,
    sell: 170,
    daily: 1.5,
    endStock: 14,
    low: 5,
    supplier: 1,
  },
  {
    name: "Salt 1kg",
    nameBn: "লবণ (১ কেজি)",
    category: "Oil & Spices",
    unit: "packet",
    buy: 36,
    sell: 42,
    daily: 5,
    endStock: 40,
    low: 10,
    supplier: 1,
  },
  {
    name: "Turmeric Powder 100g",
    nameBn: "হলুদ গুঁড়া (১০০ গ্রাম)",
    category: "Oil & Spices",
    unit: "packet",
    buy: 42,
    sell: 55,
    daily: 2,
    endStock: 24,
    low: 8,
    supplier: 1,
  },
  {
    name: "Chili Powder 100g",
    nameBn: "মরিচ গুঁড়া (১০০ গ্রাম)",
    category: "Oil & Spices",
    unit: "packet",
    buy: 55,
    sell: 70,
    daily: 2,
    endStock: 22,
    low: 8,
    supplier: 1,
  },
  {
    name: "Cumin 100g",
    nameBn: "জিরা (১০০ গ্রাম)",
    category: "Oil & Spices",
    unit: "packet",
    buy: 90,
    sell: 110,
    daily: 1,
    endStock: 14,
    low: 5,
    supplier: 1,
  },
  {
    name: "Onion",
    nameBn: "পেঁয়াজ",
    category: "Vegetables & Eggs",
    unit: "kg",
    buy: 55,
    sell: 68,
    daily: 9,
    endStock: 60,
    low: 20,
    supplier: 0,
  },
  {
    name: "Potato",
    nameBn: "আলু",
    category: "Vegetables & Eggs",
    unit: "kg",
    buy: 28,
    sell: 35,
    daily: 10,
    endStock: 75,
    low: 25,
    supplier: 0,
  },
  {
    name: "Garlic",
    nameBn: "রসুন",
    category: "Vegetables & Eggs",
    unit: "kg",
    buy: 190,
    sell: 230,
    daily: 1,
    endStock: 9,
    low: 3,
    supplier: 0,
  },
  {
    name: "Eggs (dozen)",
    nameBn: "ডিম (ডজন)",
    category: "Vegetables & Eggs",
    unit: "dozen",
    buy: 125,
    sell: 140,
    daily: 6,
    endStock: 18,
    low: 6,
    supplier: 2,
  },
  {
    name: "Milk Powder 500g",
    nameBn: "গুঁড়া দুধ (৫০০ গ্রাম)",
    category: "Dairy & Drinks",
    unit: "packet",
    buy: 395,
    sell: 430,
    daily: 1.5,
    endStock: 12,
    low: 5,
    supplier: 2,
  },
  {
    name: "Liquid Milk 1L",
    nameBn: "তরল দুধ (১ লিটার)",
    category: "Dairy & Drinks",
    unit: "packet",
    buy: 88,
    sell: 95,
    daily: 6,
    endStock: 20,
    low: 10,
    supplier: 2,
  },
  {
    name: "Mango Drink 250ml",
    nameBn: "আমের জুস (২৫০ মি.লি.)",
    category: "Dairy & Drinks",
    unit: "pcs",
    buy: 16,
    sell: 20,
    daily: 10,
    endStock: 70,
    low: 24,
    supplier: 2,
  },
  {
    name: "Cola 500ml",
    nameBn: "কোলা (৫০০ মি.লি.)",
    category: "Dairy & Drinks",
    unit: "bottle",
    buy: 33,
    sell: 40,
    daily: 8,
    endStock: 48,
    low: 12,
    supplier: 2,
  },
  {
    name: "Mineral Water 1L",
    nameBn: "মিনারেল ওয়াটার (১ লিটার)",
    category: "Dairy & Drinks",
    unit: "bottle",
    buy: 18,
    sell: 25,
    daily: 9,
    endStock: 60,
    low: 24,
    supplier: 2,
  },
  {
    name: "Tea 400g",
    nameBn: "চা পাতা (৪০০ গ্রাম)",
    category: "Snacks & Tea",
    unit: "packet",
    buy: 235,
    sell: 260,
    daily: 1.5,
    endStock: 14,
    low: 5,
    supplier: 1,
  },
  {
    name: "Marie Biscuits",
    nameBn: "মেরি বিস্কুট",
    category: "Snacks & Tea",
    unit: "packet",
    buy: 30,
    sell: 35,
    daily: 6,
    endStock: 36,
    low: 10,
    supplier: 1,
  },
  {
    name: "Potato Chips",
    nameBn: "আলুর চিপস",
    category: "Snacks & Tea",
    unit: "pcs",
    buy: 16,
    sell: 20,
    daily: 7,
    endStock: 0,
    low: 12,
    supplier: 1,
  },
  {
    name: "Instant Noodles 4-pack",
    nameBn: "ইনস্ট্যান্ট নুডলস (৪ প্যাক)",
    category: "Snacks & Tea",
    unit: "packet",
    buy: 55,
    sell: 65,
    daily: 4,
    endStock: 4,
    low: 8,
    supplier: 1,
  },
  {
    name: "Bath Soap",
    nameBn: "গোসলের সাবান",
    category: "Soap & Care",
    unit: "pcs",
    buy: 38,
    sell: 45,
    daily: 4,
    endStock: 36,
    low: 12,
    supplier: 3,
  },
  {
    name: "Toothpaste 100g",
    nameBn: "টুথপেস্ট (১০০ গ্রাম)",
    category: "Soap & Care",
    unit: "pcs",
    buy: 78,
    sell: 95,
    daily: 2,
    endStock: 16,
    low: 6,
    supplier: 3,
  },
  {
    name: "Shampoo Sachet (12)",
    nameBn: "শ্যাম্পু স্যাশে (১২টি)",
    category: "Soap & Care",
    unit: "packet",
    buy: 55,
    sell: 70,
    daily: 1.5,
    endStock: 15,
    low: 5,
    supplier: 3,
  },
  {
    name: "Washing Powder 500g",
    nameBn: "ওয়াশিং পাউডার (৫০০ গ্রাম)",
    category: "Household",
    unit: "packet",
    buy: 98,
    sell: 115,
    daily: 2,
    endStock: 18,
    low: 6,
    supplier: 2,
  },
  {
    name: "Dishwash Liquid",
    nameBn: "থালা-বাসন ধোয়ার তরল",
    category: "Household",
    unit: "pcs",
    buy: 25,
    sell: 30,
    daily: 2,
    endStock: 5,
    low: 8,
    supplier: 2,
  },
  {
    name: "Candles (pack)",
    nameBn: "মোমবাতি (প্যাকেট)",
    category: "Household",
    unit: "packet",
    buy: 28,
    sell: 35,
    daily: 1,
    endStock: 14,
    low: 5,
    supplier: 2,
  },
  {
    name: "Tissue Box",
    nameBn: "টিস্যু বক্স",
    category: "Household",
    unit: "pcs",
    buy: 55,
    sell: 70,
    daily: 1,
    endStock: 12,
    low: 4,
    supplier: 2,
  },
];

export const OWNER = {
  storeName: "রহিম জেনারেল স্টোর",
  ownerName: "রহিম উদ্দিন",
  username: "demo",
  password: "demo1234",
};

export const STAFF = [
  {
    name: "সালমা বেগম",
    username: "manager",
    password: "demo1234",
    role: "manager" as const,
  },
  {
    name: "জামাল হোসেন",
    username: "cashier",
    password: "demo1234",
    role: "cashier" as const,
  },
];

export const STORE_PROFILE = {
  name: OWNER.storeName,
  address: "১২/এ, মিরপুর-১০, ঢাকা-১২১৬",
  phone: "01711-000000",
};

export const RECEIPT_FOOTER = "ধন্যবাদ, আবার আসবেন!";

export const MONTHLY_EXPENSES: Array<{
  daysAgo: number;
  category: ExpenseCategory;
  amount: number;
  description: string;
}> = [
  { daysAgo: 27, category: "rent", amount: 15_000, description: "দোকান ভাড়া" },
  {
    daysAgo: 25,
    category: "salary",
    amount: 12_000,
    description: "ক্যাশিয়ারের বেতন",
  },
  {
    daysAgo: 22,
    category: "internet",
    amount: 800,
    description: "ইন্টারনেট বিল",
  },
  {
    daysAgo: 17,
    category: "electricity",
    amount: 3200,
    description: "বিদ্যুৎ বিল",
  },
  {
    daysAgo: 9,
    category: "maintenance",
    amount: 1200,
    description: "ফ্রিজ মেরামত",
  },
  {
    daysAgo: 4,
    category: "transport",
    amount: 600,
    description: "মাল আনার ভ্যান ভাড়া",
  },
];
